server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: p4ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
